### PR TITLE
Adding custom numbering treeprocessor

### PR DESCRIPTION
**Pull request by marko-bekhta**
hi @gunnarmorling, @gsmet,
so here's a Java version for that numbering extension. But there's one more problem is left with using it .... Because of the Asciidoctorj's `NodeConverter` tables cannot be used in sources. As it will fail with something like:

```
......
Caused by: java.lang.IllegalArgumentException: Don't know what to do with a #<Asciidoctor::Table:0x25589735>
	... 55 more
```

I somehow forgot about this one when we talked about why I wrote that Ruby version ...
(here's a related bug to this problem - https://github.com/asciidoctor/asciidoctorj/issues/472).
The issue seems to be fixed from  v1.5.4.1. but there's no asciidoctor-ant that uses such version (or higher)

### CODE REVIEW

**Comment by gsmet** [comment]
@marko-bekhta I pushed a few improvements in a follow-up commit

File: src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+			Document convertedDoc = Jsoup.parse( writer.toString() );
+
+			Elements examples = convertedDoc.getElementsByClass( "exampleblock" );
+
+			examples.forEach( this::assertExampleNumbering );
+
+		}
+	}
+
+	private void assertExampleNumbering(Element example) {
```
Comment (gsmet) [inline src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java]: It would be nice if you could test the real number and not only the pattern. You could also add a test for unnumbered sections to test that the global counter works.

You mention an issue with tables but there are no tables in the test. Could you add some? As I understand it, the issue should be fixed with the recent asciidoctorj version you are using?

File: src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java [hunk 2]
```diff
@@ -37,39 +44,39 @@ public CustomNumberingProcessor(Map<String, Object> config) {
...
-				.forEach( section -> processSection( section, NumberingIndexes.get( getSectionNumber( section ) ) ) );
+				.filter( block -> block instanceof Section )
+				.forEach( block -> processSection( (Section) block, getSectionNumberingIndexes( getSectionNumber( (Section) block ) ) ) );
 		return document;
 	}
 
-	private void processSection(AbstractBlock section, NumberingIndexes indexes) {
+	private void processSection(Section section, SectionNumberingIndexes indexes) {
 		for ( AbstractBlock block : section.getBlocks() ) {
 			if ( "example".equalsIgnoreCase( block.getNodeName() ) ) {
```
Comment (gsmet) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: Note that there's unfortunately no `Example` type... It's probably something we should try to get improved in Asciidoctorj.

File: src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java [hunk 3]
```diff
@@ -83,33 +90,32 @@ private RubyObject toRubyObject(AbstractBlock block) {
...
+	private static class SectionNumberingIndexes {
 
-		private NumberingIndexes(String sectionNumber) {
-			this.sectionNumber = sectionNumber;
-			example = new AtomicInteger( 1 );
-			table = new AtomicInteger( 1 );
-		}
+		private final int sectionNumber;
+		private AtomicInteger exampleIndex;
+		private AtomicInteger tableIndex;
```
Comment (gsmet) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: I kept the AtomicInteger but I really think they are useless. We could have simple ints incremented.

Comment (marko-bekhta) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: :) I kept them as well - at first these counters were not encapsulated and passed as method parameters for recursive methods. But now we can change it to simple ints.

File: src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java (hunk 1 above)
Comment (marko-bekhta) [inline src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java]: Yes, I'll improve the test. As for the "table issue" it will not appear for this test (but still it'll be good to have a table in the test). The problem is with the asciidoctor-ant - it is using an old version and it's failing for BV spec (as there are some tables in the docs). 
I did try to upgrade a version of asciidoctorj for  asciidoctor-ant to the latest and build a snapshot of it (asciidoctor-ant) - then all is fine.

**Comment by gsmet** [comment]
> The issue seems to be fixed from v1.5.4.1. but there's no asciidoctor-ant that uses such version (or higher)

I opened https://github.com/asciidoctor/asciidoctor-ant/pull/55 .

File: src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java (hunk 3 above)
Comment (gsmet) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: OK, let's change them to simple ints then.

File: src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java (hunk 1 above)
Comment (gsmet) [inline src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java]: > As for the "table issue" it will not appear for this test

Understood. But it would be nice to be sure we don't have a regression on this front!

As mentioned in another comment, I opened an asciidoctor-ant PR, we'll see how it goes. Thanks for confirming than upgrading asciidoctorj fixed the issue.

Comment (marko-bekhta) [inline src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java]: OK, that's great. 

I'll clean up those ints and make tests more useful, and then we just need to wait for response on asciidoctor-ant PR :) 
In the meantime (after cleanup) I'll try to add this one to HV - it should work fine there as there's 1.5.5 version of maven plugin (we would need to update the version in HV though).

Comment (gsmet) [inline src/test/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/ExampleNumberingTest.java]: Yes, feel free to upgrade it in HV. Btw nice detective work with the RubyObject thing and the caption.

**Comment by marko-bekhta** [comment]
@gsmet there's one more thing with AsciidoctorJ ... there's a problem with `section.number()` method. So that's why I've used that `toRubyObject` approach. There can be cases (like in BV spec)  when section numbers are not numbers but characters - A,B,C .... In such case `section.numbered()` returns `true` but `section.number()` will fail with something like:

```
Failed to load AsciiDoc document - cannot convert instance of class org.jruby.RubyString to int
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:338)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:427)
	at org.asciidoctor.ant.AsciidoctorAntTask.execute(AsciidoctorAntTask.java:96)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) asciidoctor: FAILED: /Users/marko/development/projects/opensource/beanvalidation-spec/sources/index.asciidoc: Failed to load AsciiDoc document - cannot convert instance of class org.jruby.RubyString to int
	at org.jruby.gen.InterfaceImpl801582152.number(org/jruby/gen/InterfaceImpl801582152.gen:13)
	at org.jruby.RubyMethod.call(org/jruby/RubyMethod.java:120)
	at RUBY.parse(/Users/marko/development/projects/opensource/beanvalidation-spec/lib/asciidoctor-ant-1.5.4-SNAPSHOT.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.parse(/Users/marko/development/projects/opensource/beanvalidation-spec/lib/asciidoctor-ant-1.5.4-SNAPSHOT.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478)
	at RUBY.load(/Users/marko/development/projects/opensource/beanvalidation-spec/lib/asciidoctor-ant-1.5.4-SNAPSHOT.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347)
	at RUBY.convert(/Users/marko/development/projects/opensource/beanvalidation-spec/lib/asciidoctor-ant-1.5.4-SNAPSHOT.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465)
	at RUBY.convert_file(/Users/marko/development/projects/opensource/beanvalidation-spec/lib/asciidoctor-ant-1.5.4-SNAPSHOT.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1579)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl804209763.convertFile(org/jruby/gen/InterfaceImpl804209763.gen:13)
```

So we probably should report this to AsciidoctorJ right ? And in the meantime I'd say that we should do something like this:

```java
	private int getSectionNumber(Section section) {
		// return the section number if the section is numbered, return a default global section number if not
		try {
			return section.numbered() ? section.number() : NOT_NUMBERED_SECTION_NUMBER;
		}
		catch (org.jruby.exceptions.RaiseException e) {
			return NOT_NUMBERED_SECTION_NUMBER;
		}
	}
```

Or if we want to use "character section numbering" in examples as well - then we probably will need to use string instead and `toRubyObject` approach. WDYT ?

File: pom.xml [hunk 4]
```diff
@@ -49,7 +49,9 @@
         <maven.compiler.source>1.8</maven.compiler.source>
         <maven.compiler.target>1.8</maven.compiler.target>
 
-        <asciidoctorj.version>1.5.3.2</asciidoctorj.version>
+        <asciidoctorj.version>1.6.0-alpha.3</asciidoctorj.version>
```
Comment (gsmet) [inline pom.xml]: I don't think it's such a good idea. Especially since it does not solve our issue.

We'll be lucky if we can get an updated asciidoctor-ant version with latest 1.5.5. I wouldn't bet on having a version with the beta.

Let's extract this change in another PR and keep it on hold for now.

File: src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+				sectionNumber == NOT_NUMBERED_SECTION_NUMBER ?
+						String.format( "%s %d: ", title, indexNumber ) :
+						String.format( "%s %d.%d: ", title, sectionNumber, indexNumber )
+		) );
+	}
+
+	private int getSectionNumber(Section section) {
+		// return the section number if the section is numbered, return a default global section number if not
+		try {
+			return section.isNumbered() ? section.getNumber() : NOT_NUMBERED_SECTION_NUMBER;
```
Comment (gsmet) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: Let's go back to using RubyObject. Not having the section "number" for appendix isn't nice.

And let's add a comment in the code to explain why we use this approach.

Comment (marko-bekhta) [inline src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java]: Ok, will do that.

File: pom.xml (hunk 4 above)
Comment (marko-bekhta) [inline pom.xml]: this solves issues with generating PDF (see https://github.com/hibernate/hibernate-validator/pull/729). So I'd say that we have next options:

- release two versions of extensions: one based on 1.5.5 another on 1.6 and use them in BV and HV corresponding.
- not use extension for HV (at least for now) and revert to 1.5.5. 
- wrap html generation of spec for BV with maven and then run something like `mvn clean package` from ant to only generate html version of spec leaving ant for everything else.

Comment (gsmet) [inline pom.xml]: You refer to an exception when generating the PDF of HV but I don't see the exception anywhere? What's the issue exactly?

Comment (marko-bekhta) [inline pom.xml]: Sorry, forgot to link the issue... Here it is:
https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/298

Comment (gsmet) [inline pom.xml]: Mmmmh OK. Looks like they messed up the PDF plugin. And they moved the 1.5 branch of the plugin to the 1.6 branch of asciidoctor-pdf :/. So we don't really have a handy solution here.

To be honest, I'm a bit skeptic of going the ant uberjar route. We already have some dependency management in our build.xml. So what I'm wondering is if we could build a asciidoctor-ant-runner that would only contain the asciidoctor-ant classes and wouldn't include the dependency. Thus we could provide them as a classpath in our ant file and this would simplify the upgrade of one of the components. I created an issue upstream to see what they think about that.

After discussing it with Gunnar, the idea would be to copy the ant task of the asciidoctor-ant project in the beanvalidation-spec project. No need for a Maven project, just put the necessary files in a ant/ directory. You can see how we used to compile java files here: https://github.com/beanvalidation/beanvalidation-spec/commit/346fdf7c10f970fb20d49e8793170b92612a129e#diff-2cccd7bf48b7a9cc113ff564acd802a8
so it should be easy to mimic it to compile the ant task. There is only one file to compile (and the antlib.xml have to also be available).

Then we would run our ant task with the necessary dependencies in the classpath. You already have a few examples on how to download a Maven dependency.

This way, we will be able to use the right dependencies and be consistent with what we do on HV with Maven.

Does it look like a good plan to you?

Comment (gsmet) [inline pom.xml]: @marko-bekhta looks like it might even be unnecessary to do the work ourselves: https://github.com/asciidoctor/asciidoctor-ant/issues/56#issuecomment-298697737

Let's see how it goes on the asciidoctor-ant front.

Comment (marko-bekhta) [inline pom.xml]: Ok that sounds good ! I'll just change the numbering part to use `toRubyObject` and leave the last commit (with upgrade to 1.6) in this PR for now.

**Comment by abelsromero** [comment]
Hi, I'd like to help here, even though Mark has everything under control ;). Mainly I want to add clarity for the *convoluted* versions on AsciidoctorJ side.
The 1.6.0 branch is in fact an pre-release branch of the stable branch with a new API for extension, all fixes from master are applied. Thing is changes are huge!! -it's a complete overhaul- and non-backward compatible.
As a result, when in need of complex extensions, we recommend using 1.6.x, but it doesn't make it beta/unstable version or means that we officially recommend always that version. Another consequence of the overhaul is that some extensions that fail in 1.5.x, work in 1.6.x, which is your case here with the `undefined method `numbered_title'` issue with PDFs.
It's true however that current 1.6.x uses Asciidoctor 1.5.4, but maybe it's time to make a new one aligned with asciidoctor (ruby) 1.5.5? (/cc @robertpanzer)

Said that, I tested @marko-bekhta branches to make sure we were not missing anything and I can confirm that the issue only appears when `CustomNumberingProcessor` is used with PDF and AsciidoctorJ 1.5.5. Other than that, without the extension or using 1.6.x it works fine, probably the extension API in 1.5.5 is doing some internal transformation that deletes the attribute but 1.6.x does it correctly.

I hope this clarifies any doubt about the versions.

PS: big kudos to @robertpanzer who engineered the whole overhaul.
